Enforced semantic versioning from bash version checker.
As much as I looked in, it seems that there is no way to package together orb code and our python script, or for that matter any external code. If I'm right, the orb will only reference the external script relative to the config. However, this means that that external script required by orb would need to be added to every project that is importing the orb from the registry. Hence, I believe that we should stick to pure Bash script within the orb YAML file for now.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -51,41 +51,64 @@ jobs:
           command: |
             echo $CURRENT_VERSION
             echo $CIRCLE_TAG
-            echo python src/publish_version_helper.py -t $CURRENT_VERSION -c $CIRCLE_TAG
-            function test() {
-              local -a posibilities=("major" "minor" "patch")
-              local -a currentv=($(echo $1 | tr "." "\n"))
-              local -a nextv=($(echo $2 | tr "." "\n"))
-              local vtype
-              
-              
-              for i in "${!currentv[@]}"
-              do
-                  for j in "${!nextv[@]}"
-                  do
-                      if [ $j -eq $i ]; then
-                          #check start
-                          if [ ${currentv[i]} -eq ${nextv[j]} ]; then
-                            break
-                          elif [ ${currentv[i]} -gt ${nextv[j]} ]; then
-                            echo ERROR: Current ${posibilities[$i]} version cannot be lower than the previous one
-                            exit 1 # terminate and indicate error
-                          else
-                            echo ${posibilities[$i]}
-                            return 0
-                          fi
-                          #check end
-                      fi
-                  done        
-              done
-            }
-            #test "1.3.22" "2.3.4" # comment test
-            #test "1.3.22" "1.4.0"
-            #test "1.3.22" "1.3.23"
-            #test "1.3.22" "0.2.4" # catches major error
-            #test "1.3.22" "1.3.4" # catches patch error
-            test $CURRENT_VERSION $NEXT_VERSION
             
+            function semanticChecker() {
+                local -a posibilities=("major" "minor" "patch")
+                local -n curr=$1 #pass arrays through reference
+                local -n next=$2
+                for (( i=0; i<=3; i++ ))
+                do
+                    if [ $i -eq 3 ]; then
+                        echo "ERROR: orb version '"${next[0]}"."${next[1]}"."${next[2]}"' already exists."
+                        exit 1
+                    elif [ ${next[$i]} -gt ${curr[$i]} ]; then
+                        if [ $((${next[$i]} - ${curr[$i]})) -eq 1 ]; then
+                            local allLeadingZeroes=true
+
+                            for (( j=$(( $i+1 )); j<3; j++ ))
+                            do
+                                if [ ${next[$j]} -eq 0 ]; then
+                                    continue
+                                else
+                                    allLeadingZeroes=false
+                                    break
+                                fi
+                            done
+
+                            if [ $allLeadingZeroes == true ]; then
+                                echo "${posibilities[$i]}"
+                                return 0
+                            else
+                                echo "ERROR: Incorrect versioning. Upon '${posibilities[$i]}' increment, the numbers following it should be set to 0."
+                                exit 1
+                            fi
+
+                        else
+                            echo "ERROR: Incorrect versioning. Increment of '${posibilities[$i]}' is larger than 1, should be equal to 1."
+                            exit 1
+                        fi
+                    elif [ ${next[$i]} -eq ${curr[$i]} ]; then
+                        continue
+                    else
+                        echo "ERROR: New '${posibilities[$i]}' release version number cannot be lower than the one from the current version."
+                        exit 1
+                    fi
+                done
+            }
+
+            function getReleaseType() {
+                local -a currentv=($(echo $1 | tr "." "\n"))
+                local -a nextv=($(echo $2 | tr "." "\n"))
+
+                if [ ${#currentv[*]} -eq ${#nextv[*]} ]; then
+                    echo $( semanticChecker currentv nextv )
+                else
+                    echo "ERROR: Current and New version declaration lengths don't match"
+                    exit 1
+                fi
+            }
+
+            getReleaseType "1.2.222" "1.3.0"
 
 
             
